FROM node:22-alpine AS build

WORKDIR /app

ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_META_PIXEL_ID
ARG NEXT_PUBLIC_TIKTOK_PIXEL_ID
ARG NEXT_PUBLIC_WHATSAPP_NUMBER
ARG NEXT_PUBLIC_CONFIRMATION_PHONE
ARG NEXT_PUBLIC_CONFIRMATION_WINDOW
ARG NEXT_PUBLIC_DISPATCH_WINDOW
ARG NEXT_PUBLIC_DELIVERY_WINDOW
ARG NEXT_PUBLIC_STANDARD_SHIPPING_FEE
ARG NEXT_PUBLIC_FREE_GIFT_NAME
ARG GIT_SHA

ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    NEXT_PUBLIC_META_PIXEL_ID=$NEXT_PUBLIC_META_PIXEL_ID \
    NEXT_PUBLIC_TIKTOK_PIXEL_ID=$NEXT_PUBLIC_TIKTOK_PIXEL_ID \
    NEXT_PUBLIC_WHATSAPP_NUMBER=$NEXT_PUBLIC_WHATSAPP_NUMBER \
    NEXT_PUBLIC_CONFIRMATION_PHONE=$NEXT_PUBLIC_CONFIRMATION_PHONE \
    NEXT_PUBLIC_CONFIRMATION_WINDOW=$NEXT_PUBLIC_CONFIRMATION_WINDOW \
    NEXT_PUBLIC_DISPATCH_WINDOW=$NEXT_PUBLIC_DISPATCH_WINDOW \
    NEXT_PUBLIC_DELIVERY_WINDOW=$NEXT_PUBLIC_DELIVERY_WINDOW \
    NEXT_PUBLIC_STANDARD_SHIPPING_FEE=$NEXT_PUBLIC_STANDARD_SHIPPING_FEE \
    NEXT_PUBLIC_FREE_GIFT_NAME=$NEXT_PUBLIC_FREE_GIFT_NAME \
    GIT_SHA=$GIT_SHA

COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

FROM node:22-alpine

WORKDIR /app
ENV NODE_ENV=production

COPY --from=build /app ./

EXPOSE 3000
CMD ["npm", "run", "start"]