export const landing = {
  sectionOrder: ["ugc", "reviews"] as const,
  hero: {
    eyebrow: "Le coffret en satin demi-soie",
    headline: "Vos cheveux, protégés toute la nuit.",
    body: "Toucher soyeux, doux sur la peau. 6 pièces, boucleur offert.",
    cta: "Commander le coffret",
    priceCaption: "paiement à la livraison",
  },
  trust: {
    freeDelivery: "Livraison gratuite sur le coffret",
    cod: "Payé à la livraison",
    codLong: "Vous payez à la réception",
    confirm: "On vous appelle pour confirmer avant l'envoi",
  },
  valueStack: {
    eyebrow: "Dans la boîte",
    title: "Six pièces pensées pour une nuit entière.",
    body: "Deux taies, un bonnet, deux chouchous et le boucleur sans chaleur offert. Un rituel complet, prêt pour ce soir.",
    imageAlt: "Coffret MELSSY ouvert avec deux taies satinées, un bonnet, deux chouchous et un boucleur sans chaleur",
    items: [
      { productId: "pillowcase-solo", quantity: 2, label: "2 taies satinées" },
      { productId: "bonnet-solo", quantity: 1, label: "1 bonnet satiné" },
      { productId: "scrunchies-solo", quantity: 2, label: "2 chouchous satinés" },
      { productId: "heatless-curler-solo", quantity: 1, label: "1 boucleur sans chaleur", gift: true },
    ],
    giftBadge: "offert",
    separateLabel: "Valeur séparée",
    coffretLabel: "En coffret",
    savingsLabel: "Vous économisez",
  },
  order: {
    productLabel: "Coffret Beauty Night Ritual",
    nameLabel: "Nom complet",
    nameError: "Saisissez votre nom complet.",
    phoneLabel: "Téléphone",
    phonePlaceholder: "06 00 00 00 00",
    phoneError: "Saisissez un numéro mobile marocain valide commençant par 06 ou 07.",
    cityLabel: "Ville",
    cityError: "Saisissez votre ville.",
    addressLabel: "Adresse",
    addressPlaceholder: "Quartier, rue, n°, point de repère",
    addressError: "Saisissez une adresse complète d'au moins 8 caractères.",
    reassurance: "On vous appelle pour confirmer avant l'envoi. Aucun paiement en ligne.",
    submitting: "Enregistrement...",
    error: "Votre commande n'a pas pu être enregistrée. Veuillez réessayer.",
    validationError: "Vérifiez votre nom, votre téléphone, votre ville et votre adresse, puis réessayez.",
    timeoutError: "Le service met trop de temps à répondre. Vérifiez votre connexion puis réessayez.",
    networkError: "Impossible de joindre le service de commande. Vérifiez votre connexion puis réessayez.",
    confirmationError: "Nous n'avons pas pu confirmer l'enregistrement de votre commande. Veuillez réessayer.",
  },
  ctas: {
    completeRitual: "Complétez votre rituel",
    viewOrderForm: "Voir le formulaire",
  },
  problem: {
    eyebrow: "Le problème",
    title: "La nuit ne devrait pas effacer ce que vous avez pris le temps de faire.",
    body: "Frottements, frisottis, boucles aplaties, longueurs moins nettes: l'oreiller peut transformer votre coiffure pendant que vous dormez. Le matin ne peut pas toujours rattraper huit heures de nuit.",
  },
  bundle: {
    eyebrow: "Dans la boîte",
    title: "Le rituel complet, prêt pour ce soir.",
    body: "Deux taies satinées, un bonnet satiné, deux chouchous satinés et un boucleur sans chaleur offert.",
  },
  satinComparison: {
    eyebrow: "Le toucher demi-soie",
    headline: "Fluide, lisse et doux sur la peau.",
    subheadline: "Sa surface satinée accompagne vos cheveux avec moins de friction et absorbe moins les soins et l'humidité que le coton.",
    blocks: [
      {
        lead: "Le coton absorbe. C'est son métier.",
        text: "On fabrique les serviettes en coton pour une raison : il boit l'eau. Votre taie d'oreiller fait exactement la même chose, huit heures par nuit. L'huile que vous appliquez le soir, l'hydratation de votre masque, votre crème de nuit — une partie finit dans le tissu. Le satin, lui, n'absorbe rien. Ce que vous mettez sur vos cheveux y reste.",
      },
      {
        lead: "Vous bougez 20 à 40 fois par nuit.",
        text: "Pas une fois. Des dizaines. À chaque mouvement, vos cheveux sont traînés sur la trame du coton — une grille rugueuse, invisible à l'œil nu. Le satin n'a pas de trame en relief : les cheveux glissent au lieu d'accrocher.",
      },
      {
        lead: "Les frisottis ne viennent pas de nulle part.",
        text: "Votre cheveu est couvert d'écailles superposées, comme des tuiles. La friction les soulève. Des écailles soulevées, c'est précisément ça, un frisottis. Voilà pourquoi vos cheveux sont souvent moins beaux au réveil qu'au moment où vous vous êtes couchée.",
      },
    ],
    closing: "Composition : 97 % polyester, 3 % élasthanne. Un satin demi-soie au tombé fluide et à l'éclat discret.",
    imageAlt: "Comparaison macro entre une trame de coton et une trame de satin, côte à côte",
  },
  preview: {
    eyebrow: "Aperçu de mise en page",
    ugcTitle: "Vos vidéos clientes.",
    ugcCards: [
      { name: "Prénom", quote: "Aperçu d'un témoignage vidéo." },
      { name: "Prénom", quote: "Aperçu d'un témoignage vidéo." },
      { name: "Prénom", quote: "Aperçu d'un témoignage vidéo." },
      { name: "Prénom", quote: "Aperçu d'un témoignage vidéo." },
      { name: "Prénom", quote: "Aperçu d'un témoignage vidéo." },
      { name: "Prénom", quote: "Aperçu d'un témoignage vidéo." },
    ],
    reviewsTitle: "Avis clientes.",
    reviewsBody: "Aperçu réservé à la validation de mise en page.",
  },
  faq: [
    ["Comment se passe le paiement ?", "Vous réglez votre commande à la livraison, après confirmation avec notre équipe."],
    ["Où livrez-vous et en combien de temps ?", "Partout au Maroc, livraison offerte sur le coffret. Le délai vous est confirmé par téléphone avant l'envoi."],
    ["Et si je ne suis pas satisfaite ?", "Vous pouvez échanger ou retourner votre coffret sous 7 jours après réception. Pour des raisons d'hygiène, les pièces doivent être non utilisées et dans leur emballage d'origine. {{contact}}, nous vous répondons rapidement."],
    ["Le rituel convient-il à tous les cheveux ?", "Il est pensé pour tous les types de cheveux. C'est un geste de douceur pour vos cheveux. Il ne remplace pas un soin professionnel."],
  ],
  ritual: {
    eyebrow: "Le rituel",
    title: "Quatre étapes, puis dormez.",
    steps: [
      { label: "LE BOUCLEUR", text: "Enroulez vos longueurs, fixez avec les chouchous." },
      { label: "LE BONNET", text: "Enfilez-le pour garder tout en place." },
      { label: "LA TAIE", text: "Posez la tête sur le satin. Moins de frottement." },
      { label: "AU RÉVEIL", text: "Déroulez : des boucles souples, sans chaleur." },
    ],
  },
  masthead: {
    brand: "MELSSY",
  },
  faqSection: {
    eyebrow: "Questions fréquentes",
    title: "Avant de commander.",
  },
  finalOrder: {
    eyebrow: "La Beauty Night Ritual™",
    title: "Le dernier geste de votre journée.",
  },
  collection: {
    eyebrow: "La collection",
    title: "Les essentiels de nuit.",
    view: "Voir la collection",
    discover: "Découvrir",
  },
  footer: {
    descriptor: "Beauty Sleep Ritual",
    links: ["Notre histoire", "Collections", "Nous contacter"],
  },
} as const;