export const landing = {
  sectionOrder: ["ugc", "reviews"] as const,
  hero: {
    eyebrow: "Le coffret Beauty Night Ritual",
    headline: "Vos cheveux, protégés toute la nuit.",
    body: "2 taies, 1 bonnet, 2 chouchous et le boucleur offert. Prêt pour ce soir.",
    cta: "Commander le coffret",
    priceCaption: "paiement à la livraison",
  },
  trust: {
    freeDelivery: "Livraison gratuite sur le coffret",
    cod: "Payé à la livraison",
    codLong: "Vous payez à la réception",
    confirm: "On vous appelle pour confirmer avant l'envoi",
    deliveryLabel: "Délai de livraison",
    deliveryTime: "[délai à confirmer]",
  },
  valueStack: {
    eyebrow: "Dans la boîte",
    title: "Six pièces pensées pour une nuit entière.",
    body: "Deux taies, un bonnet, deux chouchous et le boucleur sans chaleur offert. Un rituel complet, prêt pour ce soir.",
    imageAlt: "Coffret MELSSY ouvert avec deux taies satinées, un bonnet, deux chouchous et un boucleur sans chaleur",
    items: [
      { productId: "pillowcase-pair", label: "2 taies satinées" },
      { productId: "bonnet-solo", label: "1 bonnet satiné" },
      { productId: "scrunchies-solo", label: "2 chouchous satinés" },
      { productId: "heatless-curler-solo", label: "1 boucleur sans chaleur", gift: true },
    ],
    giftBadge: "offert",
    separateLabel: "Valeur séparée",
    coffretLabel: "En coffret",
    savingsLabel: "Vous économisez",
  },
  addons: {
    title: "Ajoutez à votre coffret",
    hint: "Optionnel. Ajouté à votre commande, livré ensemble.",
    items: ["pillowcase-pair", "extra-bonnet"],
    pricePrefix: "+",
  },
  order: {
    productLabel: "Coffret Beauty Night Ritual",
    nameLabel: "Nom complet",
    nameError: "Saisissez votre nom complet.",
    phoneLabel: "Téléphone",
    phonePlaceholder: "06 00 00 00 00",
    phoneError: "Saisissez un numéro mobile marocain valide commençant par 06 ou 07.",
    reassurance: "On vous appelle pour confirmer avant l'envoi. Aucun paiement en ligne.",
    submitting: "Enregistrement...",
    error: "Votre commande n'a pas pu être enregistrée. Veuillez réessayer.",
  },
  ctas: {
    completeRitual: "Complétez votre rituel",
    viewOrderForm: "Voir le formulaire",
  },
  upsell: {
    title: "Une seconde paire ?",
    body: "Une paire de taies satinées en plus, pour la chambre d'amis ou pour offrir. Ajoutée à votre commande, livrée ensemble.",
    accept: "Oui, ajouter à ma commande",
    decline: "Non merci, continuer",
  },
  problem: {
    eyebrow: "Le problème",
    title: "La nuit ne devrait pas effacer ce que vous avez pris le temps de faire.",
    body: "Frottements, frisottis, boucles aplaties, longueurs moins nettes: l'oreiller peut transformer votre coiffure pendant que vous dormez. Le matin ne peut pas toujours rattraper huit heures de nuit.",
  },
  bundle: {
    eyebrow: "Dans la boîte",
    title: "Le rituel complet, prêt pour ce soir.",
    body: "Deux taies satinées, un bonnet satiné, deux chouchous satinés et un boucleur sans chaleur offert.",
  },
  satinComparison: {
    eyebrow: "Pourquoi le satin",
    headline: "Ce que le satin change, nuit après nuit.",
    subheadline: "Et le matin, vous accusez vos cheveux.",
    blocks: [
      {
        lead: "Le coton absorbe. C'est son métier.",
        text: "On fabrique les serviettes en coton pour une raison : il boit l'eau. Votre taie d'oreiller fait exactement la même chose, huit heures par nuit. L'huile que vous appliquez le soir, l'hydratation de votre masque, votre crème de nuit — une partie finit dans le tissu. Le satin, lui, n'absorbe rien. Ce que vous mettez sur vos cheveux y reste.",
      },
      {
        lead: "Vous bougez 20 à 40 fois par nuit.",
        text: "Pas une fois. Des dizaines. À chaque mouvement, vos cheveux sont traînés sur la trame du coton — une grille rugueuse, invisible à l'œil nu. Le satin n'a pas de trame en relief : les cheveux glissent au lieu d'accrocher.",
      },
      {
        lead: "Les frisottis ne viennent pas de nulle part.",
        text: "Votre cheveu est couvert d'écailles superposées, comme des tuiles. La friction les soulève. Des écailles soulevées, c'est précisément ça, un frisottis. Voilà pourquoi vos cheveux sont souvent moins beaux au réveil qu'au moment où vous vous êtes couchée.",
      },
    ],
    closing: "Ce n'est pas de la soie, et nous préférons vous le dire. C'est du satin 100% polyester : il n'absorbe pas et supporte le lavage.",
    imageAlt: "Comparaison macro entre une trame de coton et une trame de satin, côte à côte",
  },
  comparison: {
    eyebrow: "MELSSY et le reste",
    title: "Un rituel pensé, pas un essentiel choisi au hasard.",
    melssyLabel: "MELSSY",
    genericLabel: "Générique",
    melssy: "Des pièces coordonnées, pensées pour se compléter dans votre soirée.",
    generic: "Un accessoire isolé, sans rituel clair ni expérience pensée autour de votre nuit.",
  },
  preview: {
    eyebrow: "Aperçu de mise en page",
    ugcTitle: "Vos vidéos clientes.",
    ugcCards: [
      { name: "Prénom", quote: "Aperçu d'un témoignage vidéo." },
      { name: "Prénom", quote: "Aperçu d'un témoignage vidéo." },
      { name: "Prénom", quote: "Aperçu d'un témoignage vidéo." },
      { name: "Prénom", quote: "Aperçu d'un témoignage vidéo." },
      { name: "Prénom", quote: "Aperçu d'un témoignage vidéo." },
      { name: "Prénom", quote: "Aperçu d'un témoignage vidéo." },
    ],
    reviewsTitle: "Avis clientes.",
    reviewsBody: "Aperçu réservé à la validation de mise en page.",
  },
  faq: [
    ["Comment se passe le paiement ?", "Vous réglez votre commande à la livraison, après confirmation avec notre équipe."],
    ["Où livrez-vous et en combien de temps ?", "Partout au Maroc, livraison offerte sur le coffret. Délai indicatif : {{deliveryTime}}. Confirmé par téléphone avant l'envoi."],
    ["Le rituel convient-il à tous les cheveux ?", "Oui. C'est un geste de douceur pour vos cheveux. Il ne remplace pas un soin professionnel."],
    ["Comment entretenir les pièces ?", "Nos pièces sont en satin 100% polyester, pensé pour supporter le lavage. Conseils d'entretien détaillés : [à confirmer]."],
  ],
  ritual: {
    eyebrow: "Le rituel",
    title: "Un geste qui suit votre soirée.",
    steps: ["Attachez avec douceur", "Préparez vos boucles", "Enveloppez vos longueurs", "Posez-vous, simplement"],
  },
  masthead: {
    brand: "MELSSY",
  },
  faqSection: {
    eyebrow: "Questions fréquentes",
    title: "Avant de commander.",
  },
  finalOrder: {
    eyebrow: "La Beauty Night Ritual™",
    title: "Le dernier geste de votre journée.",
  },
  collection: {
    eyebrow: "La collection",
    title: "Les essentiels de nuit.",
    view: "Voir la collection",
    discover: "Découvrir",
  },
  footer: {
    descriptor: "Beauty Sleep Ritual",
    links: ["Notre histoire", "Collections", "Nous contacter"],
  },
} as const;