export const media = {
  landingHero: { src: "/images/hero-reveil.png", alt: "Femme qui se réveille sur une taie d'oreiller en satin MELSSY", ratio: "4:5", intendedShot: "Femme se réveillant sur une taie satinée MELSSY", temporary: false },
  coffretBox: { src: "/images/hero-pictures.webp", alt: "Coffret MELSSY ouvert avec deux taies satinées, un bonnet, deux chouchous et un boucleur sans chaleur", ratio: "1:1", intendedShot: "Coffret MELSSY ouvert, vue carrée", temporary: false },
  heroRitual: { src: "/images/temp/satin-picture-2.webp", alt: "Les cinq pièces du coffret Beauty Night Ritual", ratio: "4:5", intendedShot: "PHOTO HERO — LES 5 PIÈCES DU COFFRET", temporary: true },
  storyNight: { src: "/images/temp/hero-rituel.svg", alt: "Femme dans une chambre apaisée", ratio: "4:5", intendedShot: "Femme reposant dans la lumière du matin", temporary: true },
  satinComparison: { src: "/images/temp/satin-comparison.svg", alt: "Comparaison macro entre une trame de coton et une trame de satin, côte à côte", ratio: "3:2", intendedShot: "Macro comparison shot of cotton weave versus satin weave", temporary: true },
  ritualDetail: { src: "/images/temp/satin-picture.webp", alt: "Coffret complet MELSSY", ratio: "3:2", intendedShot: "Les cinq pièces du coffret ensemble", temporary: true },
  problemSection: { src: "/images/probleme-brosse.png", alt: "Femme qui démêle ses cheveux abîmés avec une brosse au réveil", ratio: "4:3", intendedShot: "Woman brushing damaged hair in the morning", temporary: false },
  thankYouPackage: { src: "/images/temp/satin-picture.webp", alt: "Coffret ouvert avec les cinq pièces du rituel", ratio: "3:2", intendedShot: "PHOTO — COFFRET OUVERT, LES 5 PIÈCES", temporary: true },
  satinPink: { src: "/images/temp/satin-pink.jpg", alt: "Surface satinée rose", ratio: "3:2", intendedShot: "Détail satiné rose", temporary: true },
  collectionBonnet: { src: "/images/temp/step-bonnet.svg", alt: "Bonnet satiné", ratio: "1:1", intendedShot: "Bonnet satiné présenté sur fond neutre", temporary: true },
  collectionPillowcase: { src: "/images/temp/step-oreiller.svg", alt: "Taie d'oreiller satinée", ratio: "1:1", intendedShot: "Taie satinée dans une chambre neutre", temporary: true },
  collectionCurler: { src: "/images/temp/step-boucleur.svg", alt: "Boucleur sans chaleur", ratio: "1:1", intendedShot: "Boucleur sans chaleur présenté", temporary: true },
  collectionScrunchies: { src: "/images/temp/step-chouchou.svg", alt: "Chouchous satinés", ratio: "1:1", intendedShot: "Chouchous satinés présentés", temporary: true },
  ugc: [
    { src: "/images/temp/ugc-01.svg", alt: "Aperçu vidéo cliente 01", ratio: "9:16", intendedShot: "Vidéo verticale cliente avec accord", temporary: true },
    { src: "/images/temp/ugc-02.svg", alt: "Aperçu vidéo cliente 02", ratio: "9:16", intendedShot: "Vidéo verticale cliente avec accord", temporary: true },
    { src: "/images/temp/ugc-03.svg", alt: "Aperçu vidéo cliente 03", ratio: "9:16", intendedShot: "Vidéo verticale cliente avec accord", temporary: true },
    { src: "/images/temp/ugc-04.svg", alt: "Aperçu vidéo cliente 04", ratio: "9:16", intendedShot: "Vidéo verticale cliente avec accord", temporary: true },
    { src: "/images/temp/ugc-05.svg", alt: "Aperçu vidéo cliente 05", ratio: "9:16", intendedShot: "Vidéo verticale cliente avec accord", temporary: true },
    { src: "/images/temp/ugc-06.svg", alt: "Aperçu vidéo cliente 06", ratio: "9:16", intendedShot: "Vidéo verticale cliente avec accord", temporary: true },
  ],
} as const;
